name: Build Organicely Angular Project
on:
  push:
    branches:
      main
    tags:
      - 1.*
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    name: Install npm and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.18.0

    steps:
      - uses: actions/checkout@v2

      - name: Setting-up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verfying path
        run: ls -a

      - name: Installing dependencies
        run: |
          cd organicely
          npm install

      - name: Building
        run: |
          cd organicely
          npm run build\

      - name: Testing
        run: |
          npm test -- --no-watch --no-progress --browers=ChromeHeadlessCI

      - name: Deploying
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORGANICELY }}'
          channelId: live
          projectId: organicely